# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d4599e9b006f51b7397ca9ba27f20ef1c65def470ff123c651dc2a8b0353adde0e095b36344e9350c8a2d221ee4b1831839346d0014d4aa1fd088936d7a14b4

test:
  secret_key_base: b90cf6f82f4594ad81f90eb59d09444ef05665e3a8da8e4f522d6f6b9a93bfc4656d17a8bcb83763ecc055abccf59c4d0f661ded9faae4e094b2989226816614

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
